version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost_blog
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      url: http://localhost:2368
