app = "trendifytube-blog"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "ghost:latest"

[env]
  url = "https://trendifytube-blog.fly.dev"
  database__client = "pg"
  database__connection__host = "trendifytube-db.internal"
  database__connection__user = "postgres"
  database__connection__password = "mufEHJXX94rAeVd"
  database__connection__database = "postgres"
  database__connection__port = "5432"

[mounts]
  source = "ghost_data"
  destination = "/var/lib/ghost/content"

[deploy]
  primary_region = "cdg"
