app = "trendifytube-blog"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "ghost:latest"

[env]
  url = "https://trendifytube-blog.fly.dev"

[mounts]
  source = "ghost_data"
  destination = "/var/lib/ghost/content"

[deploy]
  primary_region = "cdg"
