- key: database__client
  value: pg
- key: database__connection__host
  fromService:
    type: pserv
    name: postgres
    property: host
- key: database__connection__database
  value: your_dbname
- key: database__connection__user
  value: your_user
- key: database__connection__password
  fromService:
    type: pserv
    name: postgres
    envVarKey: POSTGRES_PASSWORD
